In [1]:
# Numpy Arrays

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
my_arr = np.array(my_list)

In [6]:
my_arr

array([1, 2, 3])

In [7]:
my_matrix = ([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# ^the 2 square brackets indicate a 2-d array (also called a matrix!)

In [10]:
# the most common way of creating an array is:

In [13]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# NOTE: 'arange()' NOT 'ARRANGE()'!!!!

In [15]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
# other array functions:

In [17]:
## array for generating an array with all 0s

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros ((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
# ^ for creating array using a tuple; (a, b) indicating => (<rows>, <cols>)

In [21]:
# similarly:

In [22]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.ones (2)

array([1., 1.])

In [24]:
# linspace() is for creating arrays with evenly spaced vals

In [25]:
np.linspace (0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [27]:
# ^ returns 10 evenly-spaced arguments between 0 and 5 in a 1-D array

In [29]:
# for creating an identity matrix (for linear algebra); the 'I' matrices:

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
# ^ created a 4x4 I matrix

In [33]:
# for creating arrays with 5 random vals (between the range of 0-1):

In [34]:
np.random.rand(5)

array([0.33375697, 0.88044582, 0.64651373, 0.24505511, 0.60316598])

In [35]:
np.random.rand(4)

array([0.90521426, 0.42972664, 0.52577104, 0.94256366])

In [36]:
np.random.rand(5, 5)

array([[0.12119218, 0.28777157, 0.73839589, 0.36573423, 0.18416589],
       [0.03276867, 0.76720272, 0.82394179, 0.39559159, 0.01623263],
       [0.11751633, 0.30568932, 0.21951809, 0.78900658, 0.04478274],
       [0.49682156, 0.48410621, 0.55205736, 0.42596605, 0.52121057],
       [0.89098868, 0.83428572, 0.16097864, 0.9869165 , 0.31816332]])

In [37]:
# for normalized random array:

In [38]:
np.random.randn(2)

array([0.13313401, 1.15126829])

In [39]:
np.random.randn(5)

array([-0.93356155,  0.293722  , -0.07155491,  0.51514338, -0.08306614])

In [40]:
# for random integer val arrays:

In [41]:
np.random.randint(1, 100)

12

In [42]:
# ^ we got a random int between 1(inclusive) and a 100 (exclusive; thus b/w 1-99)

In [43]:
np.random.randint(1, 100, 10)

array([88,  9, 96, 12, 73, 18, 64,  4, 39,  4])

In [44]:
my_array = np.arange(25)

In [45]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
ran_array = np.random.randint(0, 50, 10)

In [47]:
ran_array

array([36, 41, 15, 49, 13, 21, 30, 31, 43, 13])

In [48]:
my_array.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
# ^ for reshaping the matrix! it will throw an error if the shape cannot possibly fit the array!
# to check compatibility, ((rows*cols) == my_array.length)? "Valid" : "Error!"

In [52]:
ran_array

array([36, 41, 15, 49, 13, 21, 30, 31, 43, 13])

In [53]:
# for finding max value in array:

In [55]:
ran_array.max()

49

In [56]:
ran_array.argmax() #returns index location of max val

3

In [57]:
# similarly for min value in array

In [58]:
ran_array.min()

13

In [59]:
ran_array.argmin()

4

In [60]:
# to get shape of vector:

In [61]:
my_array.shape

(25,)

In [62]:
my_array = my_array.reshape(5, 5)

In [64]:
my_array.shape

(5, 5)

In [65]:
# for getting array's datatype:

In [66]:
my_array.dtype

dtype('int32')

In [70]:
# for specifying namespace and avoiding typing jargon like "arr.random.randint()"

In [68]:
from numpy.random import randint

In [69]:
randint (2, 10)

2

In [71]:
# NUMPY INDEXING AND SELECTION

In [72]:
arr = np.arange(0, 11)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[8]

8

In [75]:
arr[1:5]

array([1, 2, 3, 4])

In [76]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [77]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [78]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [80]:
arr [0:5] = 100

In [81]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [82]:
arr = np.arange(0,11)

In [83]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
slice_of_arr = arr[0:6]

In [85]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [87]:
slice_of_arr[:] = 99

In [88]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [89]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [90]:
# ^ because one is the reference of the other!!! pass by reference! not by value!

In [91]:
arr_copy = arr.copy() # use THIS to copy/pass by value!!!!

In [92]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [93]:
arr_copy[:] = 100

In [94]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [95]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [97]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [98]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [99]:
arr_2d[0][0]

5

In [100]:
arr_2d[0]

array([ 5, 10, 15])

In [101]:
arr_2d[1][1]

25

In [102]:
arr_2d[2][1]

40

In [103]:
arr_2d[2, 1]

40

In [105]:
arr_2d[1:, 1:]

array([[25, 30],
       [40, 45]])

In [106]:
# Conditional Arrays:

In [107]:
arr = np.arange (1, 11)

In [108]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
arr > 5 # returns a boolean array based on conditional statement used!

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [111]:
bool_arr = arr > 5

In [112]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [115]:
arr[bool_arr] # returns only values which are true based on boolean array passed
              # as a param/value/index

array([ 6,  7,  8,  9, 10])

In [116]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [117]:
arr[arr < 3]

array([1, 2])

In [119]:
arr_2d = np.arange(50).reshape(5, 10)

In [120]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [124]:
arr_2d [2:, 5:]

array([[25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

In [125]:
# NUMPY OPERATIONS

In [126]:
# - Array with Array Ops
# - Array with Scalar Ops
# - Universal Array Ops

In [128]:
arr = np.arange (0, 11)

In [129]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [130]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [131]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [132]:
# scalars:

In [133]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [134]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [135]:
arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [136]:
arr % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [137]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [139]:
1/0 # should throw error

ZeroDivisionError: division by zero

In [141]:
arr / arr # should issue another value

C:\Users\Shahbaz\AppData\Local\Temp/ipykernel_23064/1251202028.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr # should issue another value


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [143]:
# ^ notice how it throws null here for 0/0; nan ==  'Not a Number';
# therefore, the code will continue to run as a return value (albeit null) is 
# returned

In [144]:
1 / arr

C:\Users\Shahbaz\AppData\Local\Temp/ipykernel_23064/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [145]:
# ^ similar 'inf' val returned on 1/0 but as a part of an array/matrix

In [146]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [147]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [148]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [149]:
# Universal Array functions:

In [150]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [151]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [155]:
np.max(arr) # Similar to arr.max()

10

In [156]:
arr.max()

10

In [157]:
np.min(arr) # Similar to arr.min()

0

In [158]:
arr.min()

0

In [159]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [160]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [161]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [164]:
1/np.tan(arr)

C:\Users\Shahbaz\AppData\Local\Temp/ipykernel_23064/598691722.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/np.tan(arr)


array([        inf,  0.64209262, -0.45765755, -7.01525255,  0.86369115,
       -0.29581292, -3.436353  ,  1.14751542, -0.14706506, -2.21084541,
        1.54235105])

In [165]:
np.log(arr)

C:\Users\Shahbaz\AppData\Local\Temp/ipykernel_23064/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [168]:
arr.sum()

55

In [169]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [170]:
mat.sum()

325

In [172]:
mat.std()

7.211102550927978

In [179]:
mat[: , 0]

array([ 1,  6, 11, 16, 21])

In [185]:
([(mat[:, 0]).sum,(mat[:, 1]).sum,(mat[:, 2]).sum,(mat[:, 3]).sum,(mat[:, 4]).sum])

[<function ndarray.sum>,
 <function ndarray.sum>,
 <function ndarray.sum>,
 <function ndarray.sum>,
 <function ndarray.sum>]

In [186]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [188]:
mat.sum(axis=-1)

array([ 15,  40,  65,  90, 115])